permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 乔潇
  email: cn_qxiao@163.com
  link: http://wazying.cn
  weibo: http://weibo.com/wazying
  github: http://github.com/duduool

# 站点信息
title: 乔潇的博客 
description: 乔潇的博客
url: http://wazying.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://cdszf.img45.wal8.com/img45/522527_20150708151856/143634014993.jpg
favicon: http://120.24.63.99:8889/favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: wazying.cn